// react-todo/src/App.jsx
import { useMemo, useState } from 'react';

let nextId = 1;

function raf2() {
  return new Promise((res) => requestAnimationFrame(() => requestAnimationFrame(res)));
}

export default function App() {
  const [text, setText] = useState('');
  const [tasks, setTasks] = useState([]);

  const remaining = useMemo(() => tasks.filter(t => !t.done).length, [tasks]);

  function addOne(label) {
    const v = (label ?? text).trim();
    if (!v) return;
    setTasks(prev => [...prev, { id: nextId++, text: v, done: false }]);
    setText('');
  }

  function toggleTask(id) {
    setTasks(prev => prev.map(t => (t.id === id ? { ...t, done: !t.done } : t)));
  }

  function deleteTask(id) {
    setTasks(prev => prev.filter(t => t.id !== id));
  }

  async function addN(n) {
    const t0 = performance.now();
    setTasks(prev => {
      const start = nextId;
      const arr = prev.slice();
      for (let i = 0; i < n; i++) {
        arr.push({ id: start + i, text: `Task ${start + i}`, done: false });
      }
      nextId += n;
      return arr;
    });
    await raf2();
    const t1 = performance.now();
    console.log(`React: add ${n} items (ms):`, (t1 - t0).toFixed(2));
  }

  async function deleteAll() {
    const t0 = performance.now();
    setTasks([]);
    await raf2();
    const t1 = performance.now();
    console.log('React: delete ALL items (ms):', (t1 - t0).toFixed(2));
  }

  return (
    <div style={{maxWidth: 560, margin: '40px auto', fontFamily: 'system-ui, sans-serif'}}>
      <h1 style={{textAlign:'center'}}>React To-Do</h1>

      <div style={{display:'flex', gap:8}}>
        <input
          value={text}
          onChange={e => setText(e.target.value)}
          placeholder="Add a task"
          style={{flex:1, padding:8}}
        />
        <button onClick={() => addOne()}>Add</button>
      </div>

      <div style={{display:'flex', gap:8, marginTop:8, flexWrap:'wrap'}}>
        <button onClick={() => addN(100)}>+100</button>
        <button onClick={() => addN(1000)}>+1,000</button>
        <button onClick={() => addN(10000)}>+10,000</button>
        <button onClick={() => addN(20000)}>+20,000</button>
        <button onClick={deleteAll} style={{marginLeft:'auto'}}>Delete All</button>
      </div>

      <p style={{marginTop:12}}>
        Total: {tasks.length} · Remaining: {remaining}
      </p>

      <ul style={{listStyle:'none', padding:0}}>
        {tasks.map(t => (
          <li key={t.id} style={{display:'flex', alignItems:'center', gap:8, padding:'6px 0', borderBottom:'1px solid #eee'}}>
            <input type="checkbox" checked={t.done} onChange={() => toggleTask(t.id)} />
            <span style={{flex:1, textDecoration: t.done ? 'line-through' : 'none'}}>{t.text}</span>
            <button onClick={() => deleteTask(t.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

// vue-todo/src/App.vue
<script setup>
import { ref, computed } from 'vue';

let nextId = 1;
const text = ref('');
const tasks = ref([]);

const remaining = computed(() => tasks.value.filter(t => !t.done).length);

function addOne(label) {
  const v = (label ?? text.value).trim();
  if (!v) return;
  tasks.value.push({ id: nextId++, text: v, done: false });
  text.value = '';
}

function toggleTask(id) {
  const t = tasks.value.find(t => t.id === id);
  if (t) t.done = !t.done;
}

function deleteTask(id) {
  tasks.value = tasks.value.filter(t => t.id !== id);
}

function raf2() {
  return new Promise(res => requestAnimationFrame(() => requestAnimationFrame(res)));
}

async function addN(n) {
  const t0 = performance.now();
  const start = nextId;
  // push in one tick
  for (let i = 0; i < n; i++) {
    tasks.value.push({ id: start + i, text: `Task ${start + i}`, done: false });
  }
  nextId += n;
  await raf2();
  const t1 = performance.now();
  console.log(`Vue: add ${n} items (ms):`, (t1 - t0).toFixed(2));
}

async function deleteAll() {
  const t0 = performance.now();
  tasks.value = [];
  await raf2();
  const t1 = performance.now();
  console.log('Vue: delete ALL items (ms):', (t1 - t0).toFixed(2));
}
</script>

<template>
  <div style="max-width:560px;margin:40px auto;font-family:system-ui,sans-serif;">
    <h1 style="text-align:center">Vue To-Do</h1>

    <div style="display:flex;gap:8px">
      <input v-model="text" placeholder="Add a task" style="flex:1;padding:8px" />
      <button @click="addOne()">Add</button>
    </div>

    <div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap">
      <button @click="addN(100)">+100</button>
      <button @click="addN(1000)">+1,000</button>
      <button @click="addN(10000)">+10,000</button>
      <button @click="addN(20000)">+20,000</button>
      <button @click="deleteAll" style="margin-left:auto">Delete All</button>
    </div>

    <p style="margin-top:12px">Total: {{ tasks.length }} · Remaining: {{ remaining }}</p>

    <ul style="list-style:none;padding:0">
      <li v-for="t in tasks" :key="t.id" style="display:flex;align-items:center;gap:8px;padding:6px 0;border-bottom:1px solid #eee">
        <input type="checkbox" :checked="t.done" @change="toggleTask(t.id)" />
        <span :style="{flex:1,'text-decoration': t.done ? 'line-through' : 'none'}">{{ t.text }}</span>
        <button @click="deleteTask(t.id)">Delete</button>
      </li>
    </ul>
  </div>
</template>
